[project]
name = "car-classification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.3",
    "pandas>=2.3.1",
    "scipy>=1.16.0",
    "tensorflow>=2.19.0",
]
